# Site settings
title: blog.misaunders.com
description: 'Technical writings and generic blog'
url: 'https://blog.misaunders.com'
baseurl: 'https://blog.misaunders.com/'
google_analytics: 'UA-98353274-1'
disqus_shortname: 'misaunders'

author:
  name: 'Michael Saunders'
  email: vidguide@gmail.com
  twitter_username: vidguide  
  #facebook_username: joshgerdes
  #github_username:  joshgerdes
  linkedin_username:  michael-j-saunders

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
